server:
  port: 8081
spring:
  profiles:
    active: dev
  application:
    name: post-service
  config:
    import: "optional:configserver:http://localhost:8888"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/