spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

# eureka:
#   client:
#     service-url:
#       defaultZone: "http://localhost:8070/eureka/"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

server:
  port: 8090